apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: app-cert-issuer
  namespace: kube-system
spec:
  acme:
    email: dns@vteng.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
